services:
  drone-logbook:
    image: ghcr.io/arpanghosh8453/drone-logbook:latest
    ports:
      - "8080:80"
    volumes:
      - drone-data:/data/drone-logbook
    environment:
      - DATA_DIR=/data/drone-logbook
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  drone-data:
